# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Type.create(typename: "Normal")
Type.create(typename: "Fighting")
Type.create(typename: "Flying")
Type.create(typename: "Poison")
Type.create(typename: "Ground")
Type.create(typename: "Rock")
Type.create(typename: "Bug")
Type.create(typename: "Ghost")
Type.create(typename: "Steel")
Type.create(typename: "Fire")
Type.create(typename: "Water")
Type.create(typename: "Grass")
Type.create(typename: "Electric")
Type.create(typename: "Psychic")
Type.create(typename: "Ice")
Type.create(typename: "Dragon")
Type.create(typename: "Dark")
Type.create(typename: "Fairy")

Defender.create(maintype: "Normal")
Defender.create(maintype: "Fighting")
Defender.create(maintype: "Flying")
Defender.create(maintype: "Poison")
Defender.create(maintype: "Ground")
Defender.create(maintype: "Rock")
Defender.create(maintype: "Bug")
Defender.create(maintype: "Ghost")
Defender.create(maintype: "Steel")
Defender.create(maintype: "Fire")
Defender.create(maintype: "Water")
Defender.create(maintype: "Grass")
Defender.create(maintype: "Electric")
Defender.create(maintype: "Psychic")
Defender.create(maintype: "Ice")
Defender.create(maintype: "Dragon")
Defender.create(maintype: "Dark")
Defender.create(maintype: "Fairy")

Defender.create(maintype: "Normal", subtype: "Fighting")
Defender.create(maintype: "Normal", subtype: "Flying")
Defender.create(maintype: "Normal", subtype: "Poison")
Defender.create(maintype: "Normal", subtype: "Ground")
Defender.create(maintype: "Normal", subtype: "Rock")
Defender.create(maintype: "Normal", subtype: "Bug")
Defender.create(maintype: "Normal", subtype: "Ghost")
Defender.create(maintype: "Normal", subtype: "Steel")
Defender.create(maintype: "Normal", subtype: "Fire")
Defender.create(maintype: "Normal", subtype: "Water")
Defender.create(maintype: "Normal", subtype: "Grass")
Defender.create(maintype: "Normal", subtype: "Electric")
Defender.create(maintype: "Normal", subtype: "Psychic")
Defender.create(maintype: "Normal", subtype: "Ice")
Defender.create(maintype: "Normal", subtype: "Dragon")
Defender.create(maintype: "Normal", subtype: "Dark")
Defender.create(maintype: "Normal", subtype: "Fairy")

Defender.create(maintype: "Fighting", subtype: "Flying")
Defender.create(maintype: "Fighting", subtype: "Poison")
Defender.create(maintype: "Fighting", subtype: "Ground")
Defender.create(maintype: "Fighting", subtype: "Rock")
Defender.create(maintype: "Fighting", subtype: "Bug")
Defender.create(maintype: "Fighting", subtype: "Ghost")
Defender.create(maintype: "Fighting", subtype: "Steel")
Defender.create(maintype: "Fighting", subtype: "Fire")
Defender.create(maintype: "Fighting", subtype: "Water")
Defender.create(maintype: "Fighting", subtype: "Grass")
Defender.create(maintype: "Fighting", subtype: "Electric")
Defender.create(maintype: "Fighting", subtype: "Psychic")
Defender.create(maintype: "Fighting", subtype: "Ice")
Defender.create(maintype: "Fighting", subtype: "Dragon")
Defender.create(maintype: "Fighting", subtype: "Dark")
Defender.create(maintype: "Fighting", subtype: "Fairy")

Defender.create(maintype: "Flying", subtype: "Poison")
Defender.create(maintype: "Flying", subtype: "Ground")
Defender.create(maintype: "Flying", subtype: "Rock")
Defender.create(maintype: "Flying", subtype: "Bug")
Defender.create(maintype: "Flying", subtype: "Ghost")
Defender.create(maintype: "Flying", subtype: "Steel")
Defender.create(maintype: "Flying", subtype: "Fire")
Defender.create(maintype: "Flying", subtype: "Water")
Defender.create(maintype: "Flying", subtype: "Grass")
Defender.create(maintype: "Flying", subtype: "Electric")
Defender.create(maintype: "Flying", subtype: "Psychic")
Defender.create(maintype: "Flying", subtype: "Ice")
Defender.create(maintype: "Flying", subtype: "Dragon")
Defender.create(maintype: "Flying", subtype: "Dark")
Defender.create(maintype: "Flying", subtype: "Fairy")

Defender.create(maintype: "Poison", subtype: "Ground")
Defender.create(maintype: "Poison", subtype: "Rock")
Defender.create(maintype: "Poison", subtype: "Bug")
Defender.create(maintype: "Poison", subtype: "Ghost")
Defender.create(maintype: "Poison", subtype: "Steel")
Defender.create(maintype: "Poison", subtype: "Fire")
Defender.create(maintype: "Poison", subtype: "Water")
Defender.create(maintype: "Poison", subtype: "Grass")
Defender.create(maintype: "Poison", subtype: "Electric")
Defender.create(maintype: "Poison", subtype: "Psychic")
Defender.create(maintype: "Poison", subtype: "Ice")
Defender.create(maintype: "Poison", subtype: "Dragon")
Defender.create(maintype: "Poison", subtype: "Dark")
Defender.create(maintype: "Poison", subtype: "Fairy")

Defender.create(maintype: "Ground", subtype: "Rock")
Defender.create(maintype: "Ground", subtype: "Bug")
Defender.create(maintype: "Ground", subtype: "Ghost")
Defender.create(maintype: "Ground", subtype: "Steel")
Defender.create(maintype: "Ground", subtype: "Fire")
Defender.create(maintype: "Ground", subtype: "Water")
Defender.create(maintype: "Ground", subtype: "Grass")
Defender.create(maintype: "Ground", subtype: "Electric")
Defender.create(maintype: "Ground", subtype: "Psychic")
Defender.create(maintype: "Ground", subtype: "Ice")
Defender.create(maintype: "Ground", subtype: "Dragon")
Defender.create(maintype: "Ground", subtype: "Dark")
Defender.create(maintype: "Ground", subtype: "Fairy")

Defender.create(maintype: "Rock", subtype: "Bug")
Defender.create(maintype: "Rock", subtype: "Ghost")
Defender.create(maintype: "Rock", subtype: "Steel")
Defender.create(maintype: "Rock", subtype: "Fire")
Defender.create(maintype: "Rock", subtype: "Water")
Defender.create(maintype: "Rock", subtype: "Grass")
Defender.create(maintype: "Rock", subtype: "Electric")
Defender.create(maintype: "Rock", subtype: "Psychic")
Defender.create(maintype: "Rock", subtype: "Ice")
Defender.create(maintype: "Rock", subtype: "Dragon")
Defender.create(maintype: "Rock", subtype: "Dark")
Defender.create(maintype: "Rock", subtype: "Fairy")


Defender.create(maintype: "Bug", subtype: "Ghost")
Defender.create(maintype: "Bug", subtype: "Steel")
Defender.create(maintype: "Bug", subtype: "Fire")
Defender.create(maintype: "Bug", subtype: "Water")
Defender.create(maintype: "Bug", subtype: "Grass")
Defender.create(maintype: "Bug", subtype: "Electric")
Defender.create(maintype: "Bug", subtype: "Psychic")
Defender.create(maintype: "Bug", subtype: "Ice")
Defender.create(maintype: "Bug", subtype: "Dragon")
Defender.create(maintype: "Bug", subtype: "Dark")
Defender.create(maintype: "Bug", subtype: "Fairy")


Defender.create(maintype: "Ghost", subtype: "Steel")
Defender.create(maintype: "Ghost", subtype: "Fire")
Defender.create(maintype: "Ghost", subtype: "Water")
Defender.create(maintype: "Ghost", subtype: "Grass")
Defender.create(maintype: "Ghost", subtype: "Electric")
Defender.create(maintype: "Ghost", subtype: "Psychic")
Defender.create(maintype: "Ghost", subtype: "Ice")
Defender.create(maintype: "Ghost", subtype: "Dragon")
Defender.create(maintype: "Ghost", subtype: "Dark")
Defender.create(maintype: "Ghost", subtype: "Fairy")

Defender.create(maintype: "Steel", subtype: "Fire")
Defender.create(maintype: "Steel", subtype: "Water")
Defender.create(maintype: "Steel", subtype: "Grass")
Defender.create(maintype: "Steel", subtype: "Electic")
Defender.create(maintype: "Steel", subtype: "Psychic")
Defender.create(maintype: "Steel", subtype: "Ice")
Defender.create(maintype: "Steel", subtype: "Dragon")
Defender.create(maintype: "Steel", subtype: "Dark")
Defender.create(maintype: "Steel", subtype: "Fairy")


Defender.create(maintype: "Fire", subtype: "Water")
Defender.create(maintype: "Fire", subtype: "Grass")
Defender.create(maintype: "Fire", subtype: "Electric")
Defender.create(maintype: "Fire", subtype: "Psychic")
Defender.create(maintype: "Fire", subtype: "Ice")
Defender.create(maintype: "Fire", subtype: "Dragon")
Defender.create(maintype: "Fire", subtype: "Dark")
Defender.create(maintype: "Fire", subtype: "Fairy")

Defender.create(maintype: "Water", subtype: "Grass")
Defender.create(maintype: "Water", subtype: "Electric")
Defender.create(maintype: "Water", subtype: "Psychic")
Defender.create(maintype: "Water", subtype: "Ice")
Defender.create(maintype: "Water", subtype: "Dragon")
Defender.create(maintype: "Water", subtype: "Dark")
Defender.create(maintype: "Water", subtype: "Fairy")

Defender.create(maintype: "Grass", subtype: "Electric")
Defender.create(maintype: "Grass", subtype: "Psychic")
Defender.create(maintype: "Grass", subtype: "Ice")
Defender.create(maintype: "Grass", subtype: "Dragon")
Defender.create(maintype: "Grass", subtype: "Dark")
Defender.create(maintype: "Grass", subtype: "Fairy")

Defender.create(maintype: "Electric", subtype: "Psychic")
Defender.create(maintype: "Electric", subtype: "Ice")
Defender.create(maintype: "Electric", subtype: "Dragon")
Defender.create(maintype: "Electric", subtype: "Dark")
Defender.create(maintype: "Electric", subtype: "Fairy")

Defender.create(maintype: "Psychic", subtype: "Ice")
Defender.create(maintype: "Psychic", subtype: "Dragon")
Defender.create(maintype: "Psychic", subtype: "Dark")
Defender.create(maintype: "Psychic", subtype: "Fairy")

Defender.create(maintype: "Ice", subtype: "Dragon")
Defender.create(maintype: "Ice", subtype: "Dark")
Defender.create(maintype: "Ice", subtype: "Fairy")

Defender.create(maintype: "Dragon", subtype: "Dark")
Defender.create(maintype: "Dragon", subtype: "Fairy")

Defender.create(maintype: "Dark", subtype: "Fairy")
